version: "3"
services:
  mysqldb:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=Sanket@99
      - MYSQL_DATABASE=real_estate_db 

    
  app:
    depends_on:
      - mysqldb
    build: ./Dockerfile
    ports:
      - 8080:8080
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/real_estate_db?useSSL=false"
     - spring.datasource.username=root
     - spring.datasource.password=Sanket@99
    
    

